### ISSUE TITLE
Reverse the background png (i.e. overlay/watermark on final picture)

### ISSUE THREAD

**Issue by Alex74300** [werdeil/pibooth#65]
Hi 
I am trying to reverse the background image (png) and the picture of pibooth. I would like to create a png layer over my picture. I think I need to edit a file .py but I didn't find this line.... Do you have a solution for me?

Thanks 
alex

**Comment by werdeil** [comment]
To be sure to understand, you want to have the background png above the pibooth photos instead of below?

This could be a good idea if you manage to have a good png layer

It is not easy to change for now but you can have a look at the pibooth/pictures/concatenate.py, if you find a way feel free to do a pull request

**Comment by anxuae** [comment]
First implementation, see: 55082fd9ef698fe246aa5fe28d80d0cdfafb5a10

The key `overlays` permits to define one or two PNG files with transparency areas that will be past over the final picture. Be careful that the overlay shall have the same size (or at least same aspect ratio) than the final picture:
- 2400x3600 for portrait
- 3600x2400 for landscape

**Comment by Alex74300** [comment]
Perfect! Thanks for this enhancement !
